[versions]
spigot = "1.19-R0.1-SNAPSHOT"

[libraries]
spigot = { group = "org.spigotmc", name = "spigot", version.ref = "spigot" }
spigot-api = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }